### ISSUE TITLE
Creation of the Pre-launch Landing page

### ISSUE THREAD

**Issue by AmNotADev** [freelyis/placeholder#2]
## What needs to be delivered

A completed landing page that collects emails and sends them to the newsletter subscription API. 

### How should it be done?

The form should take the email provided, submit it to the newsletter subscription API, and show the finished state. If possible, it'd be great if the page loaded out and loaded back in dramatically with the after-submit UI.

### Technical Considerations

When you're making this, trying to keep it static doesn't matter because of sending emails to the subscription API. We won't be able to just host this on GH pages, so it will need to be hosted on a service like Netlify or a droplet.

We also need to account for two different desktop/mobile layouts, but that should be _too_ hard. I'm providing the full size image which should just need to be cropped on web and mobile.

### Specs or Mocks 

Here's the [Figma file](https://www.figma.com/file/uu4aZHAmdvZjbM8Z2mMZLj/Freely?node-id=89%3A0). All copy, font colors, field colors, border radiuses, etc can be grabbed from there.

### Addition context

Here are exports of all of the assets, so you don't have to attempt to export them yourself.

![hell_tri](https://user-images.githubusercontent.com/28451173/73322234-4fd14b80-41f9-11ea-9a4e-f81c90b165be.png)
SVG Logo: [FreelyWhite.svg.zip](https://github.com/freelyis/placeholder/files/4125863/FreelyWhite.svg.zip)

**Comment by pizzafox** [comment]
Technical issue: Google Forms doesn't publicly expose a way to collect email addresses. We can embed [a little form](https://docs.google.com/forms/d/e/1FAIpQLSdvr7EwooUqAO-HM4bectqNZNhb3TOYk8wM-xSvvffDFwtkOw/viewform?usp=sf_link) into the page, but it would be with their Material Design setup.

There are plenty of other services that will collect emails though, many of which are paid.

**Comment by MattIPv4** [comment]
I think the implication with this not being static is that there would be a custom form with a server-side component that stores the email from our form in the sheet via Google's API.
